@endpoint = “http://192.168.3.239:8090"


# 获取pageRender列表
# 获取到的参数
# name 表单名字
# id 表单id     后台定义
# version 表单版本号    后台定义
# json数据
### 数据列表API
GET  {{endpoint}}/api/pageRender/list

### 数据保存API
POST {{endpoint}}/api/pageRender/page
content-type: application/json

{
    "name":"string",
    "json":"string"
}

### 数据获取API,通过id获取三个数据, name ,id ,version
GET {{endpoint}}/api/pageRender/page?id=(id)