@endpoint = http://app1.console.smallsaas.cn:8001

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDk2NjgxMDYsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0OTkyNzMwNn0.iLGksJKrVC4l-fyFSYYT3c6m4fDZ2d7HCRNATLajxDmFA6X1-kq6riT5i89DU81T45sMTd2-JvXFgmYoviRjow

#### 获取动态页面列表
GET {{endpoint}}/api/crud/lowMainPage/lowMainPages?pageNum=1&pageSize=10
Authorization:Bearer {{token}}


#### 添加页面
POST {{endpoint}}/api/crud/lowMainPage/lowMainPages
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "pageName": "TestPage002", 
    "pageTitle": "标题", 
    "formAddTitle": "新增", 
    "formViewTitle": "查看", 
    "formEditTitle": "编辑", 
    "columnAlign": "left", 
    "apiEndpoint": "/api", 
    "contentLayout": "Content", 
    "pageMinWidth": "", 
    "formDefaultContentLayout": "TitleContent", 
    "searchType": "MoreSearch", 
    "searchButtonType": "text", 
    "contentItemContainerStyle": ""
}

#### 编辑页面
PUT {{endpoint}}/api/crud/lowMainPage/lowMainPages/6
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "formAddTitle": "新增", 
    "searchType": "MoreSearch", 
    "pageTitle": "标题", 
    "formViewTitle": "查看", 
    "formDefaultContentLayout": "TitleContent", 
    "lowOperationss": [ ], 
    "lowActionss": [ ], 
    "pageName": "TestPage002", 
    "lowFilterss": [ ], 
    "lowFieldss": [ ], 
    "contentLayout": "Content", 
    "searchButtonType": "text", 
    "apiEndpoint": "/api", 
    "columnAlign": "center", 
    "formEditTitle": "编辑", 
    "id": 6, 
    "contentItemContainerStyle": ""
}


#### 加载字段
POST {{endpoint}}/addLowFields
Authorization:Bearer {{token}}
Content-Type: application/json

{
    "endpoint":"http://app1.console.smallsaas.cn:8001",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsInVzZXJUeXBlIjoxMDAsImRldlVzZXJUeXBlIjowLCJiVXNlclR5cGUiOiJTWVNURU0iLCJpYXQiOjE2NDk2Njg3MTQsImp0aSI6IjEiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTY0OTkyNzkxNH0.DDZBRJE6DE3IyS03JkHXFP4oWXM54aD95svtlXQsBExmp6EJFYsNndybvSfFJoDEuGwMePeBVTwb9O1uXEOi0A",
    "pageId":"6",
    "originApi":"/api/crud/lowActions/lowActionses"
}


#### 获取整个页面数据
GET {{endpoint}}/api/crud/lowMainPage/lowMainPages/6
Authorization:Bearer {{token}}



